# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CPSInc. iOS Application' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CPSInc. iOS Application
  pod 'Charts'
  pod 'SwiftyDropbox'
  pod 'RNCryptor', '~> 5.0'
  pod 'SwiftKeychainWrapper'
  pod "Mobile-Buy-SDK"
  
  target 'CPSInc. iOS ApplicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CPSInc. iOS ApplicationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
